### ISSUE TITLE
Please make the source for the hits in MISP configurable

### ISSUE THREAD

**Issue by jloehel** [tylabs/dovehawk#5]
It would be awesome if I could configure the value for the source in MISP for different zeek clusters. :-)

https://github.com/tylabs/dovehawk/blob/43ff4f529eceef23f83d187bce180424c5cd458b/scripts/dovehawk.zeek#L266

**Comment by tylabs** [comment]
Added config item for this issue:
global CLUSTER_ID = "dovehawk.io"; #source name for MISP sightings
